# This file was generated by LetItGo.
class Gitteams < Formula
  desc "GitTeams gives you insight into multiple repositories at once."
  homepage "https://github.com/NoUseFreak/gitteams"

  version "0.1.14"
  url "https://github.com/NoUseFreak/gitteams/releases/download/0.1.14/darwin_amd64.zip"
  sha256 "acf0f0167408bbb099cde44d844ff37931dfc51ca5f95df21c9b061f9075bd1b"

  def install
    bin.install "gitteams"
  end


  test do
    system "#{bin}/gitteams -h"
  end
end
