# This file was generated by LetItGo.
class Gitteams < Formula
  desc "GitTeams gives you insight into multiple repositories at once."
  homepage "https://github.com/NoUseFreak/gitteams"

  version "0.1.11"
  url "https://github.com/NoUseFreak/gitteams/releases/download/0.1.11/darwin_amd64.zip"
  sha256 "0bf78dccd5d98dbdc57d7c2be6e998b068bd3e6ee1c436e2cce55bc8d9f64462"

  def install
    bin.install "gitteams"
  end


  test do
    system "#{bin}/ -h"
  end
end
