# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projecthelper < Formula
  desc "Project helper tries to save time"
  homepage "https://github.com/nousefreak/projecthelper"
  version "0.1.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.10/projecthelper_Darwin_arm64.tar.gz"
      sha256 "c66463c667b6768e5fe31ffe1c0013bf76bcefa4454d304be59ab7291458e4a4"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.10/projecthelper_Darwin_x86_64.tar.gz"
      sha256 "4a487772b8a68026b445737650703dcec768a7afc2531d6d03da2405cc4968d7"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.10/projecthelper_Linux_x86_64.tar.gz"
      sha256 "ea17273a465d48c646ac95324013e21a714a1b24c3cdbb111c811bf05d2a3bd9"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.10/projecthelper_Linux_arm64.tar.gz"
      sha256 "db7db98ef40a2e50697956b952e6b2aa10b0cec32b6a719684ac151a5886e2ef"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  test do
    system "#{bin}/projecthelper help"
  end
end
