# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projecthelper < Formula
  desc "Project helper tries to save time"
  homepage "https://github.com/nousefreak/projecthelper"
  version "0.1.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.6/projecthelper_Darwin_x86_64.tar.gz"
      sha256 "5f267cd1f62c6c54ae9f7fe4726f1d3d4bfa46c614d8226b4d5016de18abfb66"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.6/projecthelper_Darwin_arm64.tar.gz"
      sha256 "48a2118bf94c3f2c36b3a419b3d8e67157d3b83a0b44de50c07b8c4c5794833a"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.6/projecthelper_Linux_arm64.tar.gz"
      sha256 "8ad898dbc41956dd02737b6cb9f3eaa43dad5a101768e27ee793c3d7cff6e6de"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.6/projecthelper_Linux_x86_64.tar.gz"
      sha256 "0fc782a227accf6b91dc49712753627df8a8ba752414024b05412b93929a8f0d"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  test do
    system "#{bin}/projecthelper help"
  end
end
