# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Projecthelper < Formula
  desc "Project helper tries to save time"
  homepage "https://github.com/nousefreak/projecthelper"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.2/projecthelper_Darwin_arm64.tar.gz"
      sha256 "e9eead2335628a94fa563088bd75052903f6218cd1d0c175dada3c8601cc9ece"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.2/projecthelper_Darwin_x86_64.tar.gz"
      sha256 "465e9c872e594ae16f25089adc8f6ddcbf205a15ec0a22bd27d0afcfd91b7892"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.2/projecthelper_Linux_x86_64.tar.gz"
      sha256 "f31bd25e75203d2bcbda1f7bab9187ba5c55a4b62c68475c05e3587128b4d83c"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/projecthelper/releases/download/v0.1.2/projecthelper_Linux_arm64.tar.gz"
      sha256 "c98c6b2447305b8845a3943db97f3a850a2d9d4913506b285ac8d1ca7aedf5e6"

      def install
        bin.install "projecthelper"
        man1.install "manpages/projecthelper.1.gz"
      end
    end
  end

  test do
    system "#{bin}/projecthelper help"
  end
end
