# This file was generated by LetItGo.
class Sawsh < Formula
  desc "SSH wrapper for aws to make your life easier."
  homepage "https://github.com/NoUseFreak/sawsh"

  version "1.0.0"
  url "https://github.com/NoUseFreak/sawsh/releases/download/1.0.0/darwin_amd64.zip"
  sha256 "be794324a61f6f70ff8a5fa16c325248beb90eee1d4b7352d7d08ee9856b51db"

  def install
    bin.install "sawsh"
  end


  test do
    system "#{bin}/sawsh -h"
  end
end
