# This file was generated by LetItGo.
class Sdf < Formula
  desc "sdf for the lazy developer"
  homepage "https://github.com/NoUseFreak/sdf"

  version "0.2.1"
  url "https://github.com/NoUseFreak/sdf/releases/download/0.2.1/darwin_amd64.zip"
  sha256 "11e67442c726217d78bf0d3d070a1b3452e85ff334433d68fcd3612a5da763bb"

  def install
    bin.install "sdf"
  end


  test do
    system "#{bin}/sdf -h"
  end
end
