# This file was generated by LetItGo.
class Sdf < Formula
  desc "sdf for the lazy developer"
  homepage "https://github.com/NoUseFreak/sdf"

  version "0.1.0"
  url "https://github.com/NoUseFreak/sdf/releases/download/0.1.0/darwin_amd64.zip"
  sha256 "6d9684918e1c91cb4bd2cf8dad45ebe30c5be5a5e933a9a1668da48eed426e88"

  def install
    bin.install "sdf"
  end


  test do
    system "#{bin}/sdf -h"
  end
end
