# This file was generated by LetItGo.
class Sdf < Formula
  desc "sdf for the lazy developer"
  homepage "https://github.com/NoUseFreak/sdf"

  version "0.1.2"
  url "https://github.com/NoUseFreak/sdf/releases/download/0.1.2/darwin_amd64.zip"
  sha256 "9e2c8a35e72bc8465d07938fe39b92212908ac80f0f4dc99f5ba1b66e05480b7"

  def install
    bin.install "sdf"
  end


  test do
    system "#{bin}/sdf -h"
  end
end
