# This file was generated by LetItGo.
class Sops64 < Formula
  desc "SSH wrapper for aws to make your life easier."
  homepage "https://github.com/NoUseFreak/sops64"

  version "0.1.4"
  url "https://github.com/NoUseFreak/sops64/releases/download/0.1.4/darwin_amd64.zip"
  sha256 "d468c784e6c35010a2efa3df2d8f0c5833a71a3b57bab133da46b265e64dd897"

  def install
    bin.install "sops64"
  end


  test do
    system "#{bin}/ -h"
  end
end
