# This file was generated by LetItGo.
class WaitForIt < Formula
  desc "Wait for a service to become available."
  homepage "https://github.com/NoUseFreak/wait-for-it"

  version "0.1.0"
  url "https://github.com/NoUseFreak/wait-for-it/releases/download/0.1.0/darwin_amd64.zip"
  sha256 "e2f93b0e4650851d5e017bd30c1d2fdb4ed96c8e91af66b6d8d53048ff080016"

  def install
    bin.install "wait-for-it"
  end


  test do
    system "#{bin}/ -h"
  end
end
