# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdir < Formula
  desc "Warpdir is a simple command line tool to create and manage shortcuts to directories"
  homepage "https://github.com/nousefreak/warpdir"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Darwin_arm64.tar.gz"
      sha256 "f37ec6997b42913ac904914cde68ff537c309fd8d6b03aa3d126cc1792426215"

      def install
        bin.install "warpdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Darwin_x86_64.tar.gz"
      sha256 "3e06d5065283f2d021e85f9593324d09c326fa700491c266b3836d0ef090de2d"

      def install
        bin.install "warpdir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Linux_arm64.tar.gz"
      sha256 "43c57401a0ce315a268b7054b8b5af318ed9be06211d2addebfba31776e34508"

      def install
        bin.install "warpdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Linux_x86_64.tar.gz"
      sha256 "eb49a18dd9f19c14b418001295e974f5ae7445441d12b98241eea9f0d6dd4503"

      def install
        bin.install "warpdir"
      end
    end
  end

  test do
    system "#{bin}/warpdir help"
  end
end
