# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdir < Formula
  desc "Warpdir is a simple command line tool to create and manage shortcuts to directories"
  homepage "https://github.com/nousefreak/warpdir"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v1.0.7/warpdir_Darwin_arm64.tar.gz"
      sha256 "16c1debea7f9d023ac795bdf5e314e6b23c84cbd0133da68fa495c8d08e7099a"

      def install
        bin.install "warpdir"
        bash_completion.install "completions/warpdir.bash" => "warpdir"
        zsh_completion.install "completions/warpdir.zsh" => "_warpdir"
        fish_completion.install "completions/warpdir.fish"
        man1.install "manpages/warpdir.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v1.0.7/warpdir_Darwin_x86_64.tar.gz"
      sha256 "30638356353cc7ae880686e1f53c481c3c368fb7d761d4301dea38b0f465ec35"

      def install
        bin.install "warpdir"
        bash_completion.install "completions/warpdir.bash" => "warpdir"
        zsh_completion.install "completions/warpdir.zsh" => "_warpdir"
        fish_completion.install "completions/warpdir.fish"
        man1.install "manpages/warpdir.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v1.0.7/warpdir_Linux_x86_64.tar.gz"
      sha256 "239e48eb38da4f41613b1bdc4a01e315aceb05d9739e82f02411285a3b4240ad"

      def install
        bin.install "warpdir"
        bash_completion.install "completions/warpdir.bash" => "warpdir"
        zsh_completion.install "completions/warpdir.zsh" => "_warpdir"
        fish_completion.install "completions/warpdir.fish"
        man1.install "manpages/warpdir.1.gz"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v1.0.7/warpdir_Linux_arm64.tar.gz"
      sha256 "06690fdce1bd2a64b7fc5dd96b570b957dd8650b2382a8c648e178baaa9decd6"

      def install
        bin.install "warpdir"
        bash_completion.install "completions/warpdir.bash" => "warpdir"
        zsh_completion.install "completions/warpdir.zsh" => "_warpdir"
        fish_completion.install "completions/warpdir.fish"
        man1.install "manpages/warpdir.1.gz"
      end
    end
  end

  test do
    system "#{bin}/warpdir help"
  end
end
