# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Warpdir < Formula
  desc "Warpdir is a simple command line tool to create and manage shortcuts to directories"
  homepage "https://github.com/nousefreak/warpdir"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Darwin_x86_64.tar.gz"
      sha256 "8e4179b1f78f4a157544bd79ab445a35b44b92d55e24eb56497fdb375639db55"

      def install
        bin.install "warpdir"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Darwin_arm64.tar.gz"
      sha256 "0b4db2873d0996d76df038e9a22dd0b546e99c6c3db293b30923e3c8f46e18f5"

      def install
        bin.install "warpdir"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Linux_arm64.tar.gz"
      sha256 "056a4bfaf10f55997da80b38c26bb7e02bcf57839ba7427eb08fe90e6bcc796e"

      def install
        bin.install "warpdir"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/warpdir/releases/download/v0.1.1/warpdir_Linux_x86_64.tar.gz"
      sha256 "bade3eb11849b78d0947ba8a25c37134843e04d5d3411cd0984503a8ae9529dc"

      def install
        bin.install "warpdir"
      end
    end
  end

  test do
    system "#{bin}/warpdir help"
  end
end
