# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WatchUp < Formula
  desc "Watch-up is a simple url monitoring tool that checks if a website is up or down."
  homepage "https://github.com/nousefreak/watch-up"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/NoUseFreak/watch-up/releases/download/0.1.0/watch-up_Darwin_arm64.tar.gz"
      sha256 "d37eb844ad981b539c0c144717a01ad5f898c38120a717a524593bc96ad15936"

      def install
        bin.install "watch-up"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/watch-up/releases/download/0.1.0/watch-up_Darwin_x86_64.tar.gz"
      sha256 "ec1a2cc31af115a1333bdb868bdf56d115351c3dd93d118d6032d1dcc33a6b5a"

      def install
        bin.install "watch-up"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/NoUseFreak/watch-up/releases/download/0.1.0/watch-up_Linux_x86_64.tar.gz"
      sha256 "1863a5985a62b0304722bfb02b062e90e78beb30edd5f8eac5aebb72e2efaa85"

      def install
        bin.install "watch-up"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/NoUseFreak/watch-up/releases/download/0.1.0/watch-up_Linux_arm64.tar.gz"
      sha256 "8756f363b3a6d0c69536193d9611477f70edbe0c50a5511bdadd81919398bffa"

      def install
        bin.install "watch-up"
      end
    end
  end

  test do
    system "#{bin}/watch-up help"
  end
end
